version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql_marvel
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_marvel
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      - PMA_ARBITARY=1

  www:
    build: php
    container_name: www_marvel
    ports:
      - 8741:80
    volumes:
      - ./php/vhosts:/etc/apache2//sites-enabled
      - ./:/var/www
    networks:
      - dev

  frontapp:
    build: ./front
    container_name: front_marvel
    ports:
      - 4200:80
    links:
      - www

networks:
  dev:
volumes:
  db-data:
